version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-network

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-network

  students-exams-server:
    build:
      context: ./students-exams-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - eureka
    networks:
      - my-network

  students-exams-frontend:
    build:
      context: ./students-exams-frontend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - students-exams-server
      - eureka
    networks:
      - my-network

  teacher-exams-application:
    build:
      context: ./teacher-exams-application
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - eureka
    networks:
      - my-network

# Define the custom network
networks:
  my-network:
    driver: bridge
